### ISSUE TITLE
Can't access behind my reverse proxy

### ISSUE THREAD

**Issue by johnnyasantoss** [cryptosharks131/lndg#88]
Hey, I've tried to set up my reverse proxy to have lndg running with my other services and I keep getting this error (after login):
![image](https://user-images.githubusercontent.com/14189387/179031266-4f420da4-1b32-4dbf-b6ea-c777cc164435.png)

I'm passing the `-ip` parameter with the domain on the `initialize.py` script, but it doesn't work. From the info on the error page, it seems that it's missing some config on the Django side

**Comment by johnnyasantoss** [comment]
Question: should the initialize script be called every time the container restarts?

I'm going to try the change you proposed.

**Comment by johnnyasantoss** [comment]
When adding the `CSRF_TRUSTED_ORIGINS` to the initialize.py and making it the same as `ALLOWED_HOSTS` I received an error from Django saying that the protocol is also required. I think it would be best to have a way to derive allowed_hosts from the actual trusted origins

```log
lndg    | Exception in thread django-main-thread:
lndg    | Traceback (most recent call last):
lndg    |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
lndg    |     self.run()
lndg    |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
lndg    |     self._target(*self._args, **self._kwargs)
lndg    |   File "/usr/local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
lndg    |     fn(*args, **kwargs)
lndg    |   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
lndg    |     self.check(display_num_errors=True)
lndg    |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 558, in check
lndg    |     raise SystemCheckError(msg)
lndg    | django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:
lndg    | 
lndg    | ERRORS:
lndg    | ?: (4_0.E001) As of Django 4.0, the values in the CSRF_TRUSTED_ORIGINS setting must start with a scheme (usually http:// or https://) but found lndg.baxatinha.duckdns.org. See the release notes for details.
lndg    | 
lndg    | System check identified 1 issue (0 silenced).
```

**Comment by johnnyasantoss** [comment]
When adding the `CSRF_TRUSTED_ORIGINS` to the initialize.py and making it the same as `ALLOWED_HOSTS` I received an error from Django saying that the protocol is also required. I think it would be best to have a way to derive allowed_hosts from the actual trusted origins

```log
lndg    | Exception in thread django-main-thread:
lndg    | Traceback (most recent call last):
lndg    |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
lndg    |     self.run()
lndg    |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
lndg    |     self._target(*self._args, **self._kwargs)
lndg    |   File "/usr/local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
lndg    |     fn(*args, **kwargs)
lndg    |   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
lndg    |     self.check(display_num_errors=True)
lndg    |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 558, in check
lndg    |     raise SystemCheckError(msg)
lndg    | django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:
lndg    | 
lndg    | ERRORS:
lndg    | ?: (4_0.E001) As of Django 4.0, the values in the CSRF_TRUSTED_ORIGINS setting must start with a scheme (usually http:// or https://) but found myserver.local. See the release notes for details.
lndg    | 
lndg    | System check identified 1 issue (0 silenced).
```

**Comment by cryptosharks131** [comment]
Did you include the `http://` or `https://` prefix in the `CSRF_TRUSTED_ORIGINS`?

**Comment by cryptosharks131** [comment]
In `v1.3.0` I have added an option to `initialize.py` so that you can easily include trusted CSRF origins with a docker install.

`initialize.py -csrf "'https://hostname1', 'https://ipaddress1'"`

**Comment by johnnyasantoss** [comment]
It works! Before I've manually added my host to the initialize file but this is better. Thanks
